# Generated by Django 4.2.3 on 2023-07-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name_plural': 'UserTokens'},
        ),
    ]
