# Generated by Django 4.2.3 on 2023-07-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='series_posts', to='blog_app.post'),
        ),
    ]
